version: '3.5'

services:

   backend:
      build: ml-kurkkumopo-backend/
      ports: 
       - 5000:5000
      container_name: backend_c
      volumes:
       - model:/src/model
      depends_on:
       - training

   frontend:
      build: ml-kurkkumopo-frontend/
      ports:
       - 3000:3000
      container_name: frontend_c

   training:
      build: ml-kurkkumopo-training/
      volumes:
       - model:/src/model
       - imgs:/src/imgs
      container_name: training_c

volumes:
 model:
 imgs:
